define([], function(){
  var MemoryData = [{
      memTitle: 'So many memories...',
      memSlug: 'seattle',
      memDesc: ['Though full of love, these memories are only half complete without my other half! Since I am only one half of the equation, I’m sending all my love to you to make it all complete!',
                'We have so many wonderful, beautiful memories together in this corner of the world it’s hard to capture them all! But just walking through these streets instantly takes me back down memory lane, around every corner is yet another time that I have fallen even more deeply in love with you.',
                'With so many years to come, and so many adventures yet to be had, I cannot wait to experience them each with you. As we create new memories, let’s remember those that have built our foundation!',
                'These are just a few... <3'],
      memCoverImg: 'imgs/covers/needle.jpg',
      assocMemImgs: ['imgs/assocMems/th/IMG_1352.jpg',
                     'imgs/assocMems/th/IMG_1358.jpg',
                     'imgs/assocMems/th/IMG_1363.jpg']
    },{
      memTitle: 'Happy Valentine\'s Day!!',
      memSlug: 'vday2016',
      memDesc: ['I am truly so blessed to have you in my life, here are just a few of the loving memories we have created together in the last few months! <3'],
      memCoverImg: 'imgs/covers/vday_2016.jpg',
      assocMemImgs: ['imgs/assocMems/th/20151011_103301.jpg',
          'imgs/assocMems/th/20151011_165512.jpg',
          'imgs/assocMems/th/20151024_124539.jpg',
          'imgs/assocMems/th/20150906_124326.jpg',
          'imgs/assocMems/th/20151027_205325.jpg',
          'imgs/assocMems/th/20151211_103732.jpg',
          'imgs/assocMems/th/20151211_155258.jpg',
          'imgs/assocMems/th/20151211_185229.jpg',
          'imgs/assocMems/th/20151215_212436.jpg',
          'imgs/assocMems/th/20151219_171713.jpg',
          'imgs/assocMems/th/20151221_202107.jpg',
          'imgs/assocMems/th/20151221_202121.jpg',
          'imgs/assocMems/th/20151221_202125(0).jpg',
          'imgs/assocMems/th/20160104_123548.jpg',
          'imgs/assocMems/th/20160210_154135.jpg',
          'imgs/assocMems/th/20150704_201449.jpg',
          'imgs/assocMems/th/20150817_144912.jpg',
          'imgs/assocMems/th/20150817_170420.jpg',
          'imgs/assocMems/th/20150817_172834.jpg'
      ]
    },{
      memTitle: 'Pike Place Market',
      memSlug: 'pikePlace',
      memDesc: ['Whether it’s a sunny summer day, a chilly winter night, or someone’s special day, we always find a good time at Seattle’s best a market! From sticky walls to underground bars, from corner coffee shops to late-night-pre-departure adventures we have so many memories here.',
                'While it may be a Seattle icon, it just seems uniquely ours every time I walk through here, never the same without you.'],
      memCoverImg: 'imgs/covers/pikePlace2.jpg',
      assocMemImgs: ['imgs/assocMems/th/pikePlace_1.jpg',
                     'imgs/assocMems/th/pikePlace_2.jpg',
                     'imgs/assocMems/th/pikePlace_1a.jpg',
                     'imgs/assocMems/th/pikePlace_3.jpg',
                     'imgs/assocMems/th/pikePlace_4a.jpg']
    },{
      memTitle: 'Fun times at Alki',
      memSlug: 'alki',
      memDesc: ['From the time we first discovered “Ketchup” Pad Thai to bike rides to boat rides, this western tip of Seattle is where we went to get away while still in the city. Definitely my favorite beach IN Seattle, I love sharing this niche boardwalk scene with you!',
                'From adoring the charm of little beach houses, to openly judging the ugly modern condos, from sipping IPAs to (me) getting COVERED in ice cream, this place is full of memories!',
                'Whether we ride our bikes like civil pedestrians or go completely off the beaten path as we do, we always seem to end up at exactly the right place, side by side!'],
      memCoverImg: 'imgs/covers/alkiBeach.jpg',
      assocMemImgs: ['imgs/assocMems/th/alki_0.jpg',
                     'imgs/assocMems/th/alki_1.jpg',
                     'imgs/assocMems/th/alki_2.jpg']
    },{
      memTitle: 'Macklemore at the Key Arena',
      memSlug: 'keyArena',
      memDesc: ['For the rest of my days I will always remember the most epic concert of all time and the incredible, thoughtful, love of my life that made it happen. To this day I do not know how you managed to pull it off but it is by far and again my favorite memory at the Key!',
                'The last show of THE HEIST tour in the home town on my birthday and he laid it ALL out there! And we felt it, with every beat and every rhyme, like our hearts until the end of time!'],
      memCoverImg: 'imgs/covers/keyArena.jpg',
      assocMemImgs: ['imgs/assocMems/th/keyArena_1.jpg',
                     'imgs/assocMems/th/keyArena_2.jpg',
                     'imgs/assocMems/th/keyArena_3.jpg']
    },{
      memTitle: 'Sushi with Sheela at Shilla and Beyond',
      memSlug: 'sushi',
      memDesc: ['While this is my favorite sushi place when ranked my namesake, I love that we have toured around Seattle, the country, and the world in search of delectable sushi! From conveyer belts to gourmet, from traditional to fusion to uniquely Kenyan, sushi brings us together wherever we are.',
                'Perhaps my favorite of all is the first time I took you to sushi, you may have been doubtful but you were certainly unafraid! When you dove in (and liked it! (nay LOVED it (PARENTHESIS!!))) I knew then and there you had potential to be the one!'],
      memCoverImg: 'imgs/covers/sushiTimes.jpg',
      assocMemImgs: ['imgs/assocMems/th/sushi_2.jpg',
                     'imgs/assocMems/th/sushi_3.jpg']
    },{
      memTitle: 'Us Being Goofballs',
      memSlug: 'goofs',
      memDesc: ['There is no sound as sweet as the sound of your laughter and I will do most things to hear it, though most often it seems I climb on top of things and act like a crazy person! The point is that we have fun together and in these countless moments we let our inner children out in ways we don’t with other people.',
                'Wherever we are we are able to naturally and completely be ourselves in every way, both silly and serious. You allow me to be the goofball that I am and you become a goofball right back and I love it!'],
      memCoverImg: 'imgs/covers/goofs.jpg',
      assocMemImgs: ['imgs/assocMems/th/onThings_3.jpg',
                     'imgs/assocMems/th/onThings_2.jpg',
                     'imgs/assocMems/th/onThings_1.jpg',
                     'imgs/assocMems/th/onThings_4.jpg',
                     'imgs/assocMems/th/goofs_2.jpg',
                     'imgs/assocMems/th/goofs_1.jpg']
    },{
      memTitle: 'Sounders at Centurylink Field',
      memSlug: 'CenturyLink',
      memDesc: ['My one and only futbol OR football experience in perhaps the loudest stadium ever and it was most definitely AMAZEBALLS!! It was an exhibition match and those Spanish jerks didn’t even let us win on our home turf but you wouldn’t have known it from the crowd!',
                'We weren’t able to get beers because of our silly vertical Washington IDs but who needed it when the match was that close? Not to mention when our seats were closer still! :D'],
      memCoverImg: 'imgs/covers/centuryLink.jpg',
      assocMemImgs: ['imgs/assocMems/th/centuryLink_1.jpg',
                     'imgs/assocMems/th/centuryLink_2.jpg',
                     'imgs/assocMems/th/centuryLink_3.jpg',
                     'imgs/assocMems/th/centuryLink_4.jpg']
    },{
      memTitle: 'The Seattle Water Front',
      memSlug: 'waterFront',
      memDesc: ['Even when under construction, the boardwalk here is my favorite place to simply stroll with you here in the city. With the more popular eclectic shops to the countless hidden gems tucked away in the bowels of the piers I could walk and shop and talk with you here for hours on end!',
                'With so many memories together at the waterfront of Seattle it’s impossible NOT to think of you and us when even coming close to the water’s edge. From aquatic creatures, peer perched wheels, to cedar clad entertainment, just when we think we’ve seen and done it all there is ever more yet to experience!'],
      memCoverImg: 'imgs/covers/waterFront.jpg',
      assocMemImgs: ['imgs/assocMems/th/waterFront_2.jpg',
                     'imgs/assocMems/th/waterFront_3.jpg',
                     'imgs/assocMems/th/waterFront_4.jpg',
                     'imgs/assocMems/th/waterFront_0.jpg',
                     'imgs/assocMems/th/waterFront_1.jpg']
    },{
      memTitle: 'Our Beach: Richmond Beach',
      memSlug: 'ourBeach',
      memDesc: ['Then there is my favorite beach of all, while technically not within the city limits, this is where our story really started to take off! Already it is a Mecca of our love as we frequently return to remember our roots together.',
                'From freezing nights where I awkwardly make a fool of myself, to hot summer days wading into the sound, to a summer night where we got naughty in “the love shack”, I will cherish each of our memories in this place for the rest of my days!',
                'Perhaps best of all, this is where Solid as a Rock became our song for good!'],
      memCoverImg: 'imgs/covers/richmond.jpg',
      assocMemImgs: ['imgs/assocMems/th/richmond_1.jpg',
                     'imgs/assocMems/th/richmond_2.jpg',
                     'imgs/assocMems/th/richmond_3.jpg']
    },{
      memTitle: 'Quinault Quinault Quinault',
      memSlug: 'quinault',
      memDesc: ['Far from the hustle and bustle of city life, for us, this hidden gem is the crown jewel of the PNW. From the gorgeous blue lake, to the winding river, to the countless hills tucking away untold wonders, the magic never seems to end! So much so that together we decided it was fit for the most magical night of our lives which we would share with our family and friends.',
                'These woods may be sacred to others, but I know that none hold Quinault in their hearts the way we do!'],
      memCoverImg: 'imgs/covers/quinault.jpg',
      assocMemImgs: ['imgs/assocMems/th/quinault_1.jpg',
                     'imgs/assocMems/th/quinault_2.jpg',
                     'imgs/assocMems/th/quinault_3.jpg',
                     'imgs/assocMems/th/quinault_4.jpg',
                     'imgs/assocMems/th/quinault_5.jpg']
    },{
      memTitle: 'But of course there is the fact... ',
      memSlug: 'more',
      memDesc: ['That only a fraction of our loving memories are within the city, or even in the Pacific Northwest…'],
      memCoverImg: '',
      assocMemImgs: ['imgs/memsOutOfSeattle/th/IMG_0117.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_0123.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_0126.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_0265.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_0374.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_0407.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1102.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1103.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1111.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1194.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1259.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1291.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1302.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1303.jpg',
                     // 'imgs/memsOutOfSeattle/th/IMG_1485.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1495.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1533.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1564.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_1575.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_2895.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_2994.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_3067.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_4060.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_4066.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_4276.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_5598.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_5972.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_7012.jpg',
                     'imgs/memsOutOfSeattle/th/IMG_7023.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0249.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0332.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0365.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0372.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0387.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0611.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0730.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0744.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0797.jpg',
                     'imgs/memsOutOfSeattle/th/SAM_0814.jpg']
    }];
    return MemoryData;
});